# name: cibuild
# on:
#   push:
#     branches: [ main ]
    
name: Merge PRs
on:
  pull_request:
    types:
#       - opened
      - closed
#       - edited
#       - reopened
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Delete merged branch
        uses: koj-co/delete-merged-action@master
        with:
          branches: "!development"
        env:
          GITHUB_TOKEN: "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"
    

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.

