# name: Merge PRs
# on: 
#   push:
#     branches:
#       - main
      
# jobs:
#   say_hello:
#     runs-on: ubuntu-latest
#     steps:
#       - run: |
#           echo "Hello !"
#           echo "Hii!"


name: Merge PRs
on:
  pull_request:
    types:
#       - opened
      - closed
#       - edited
#       - reopened
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Delete merged branch
        uses: koj-co/delete-merged-action@master
        with:
          branches: "!development"
        env:
          GITHUB_TOKEN: "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"
