name: MergePRs
on:
  pull_request:
    branches: [development]
    types: [closed]
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Delete merged branch 
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: koj-co/delete-merged-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          

# name: Merge PRs
# on:
#   pull_request:
#     types:
#       - closed
# jobs:
#   automerge:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Delete merged branch
#         uses: koj-co/delete-merged-action@master
#         with:
#           branches: "!development, !main"
#         env:
#           GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"






# name: CI
# on:
#   push:
#     branches: [ main ]
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
