name: TestingPath
on:
  push:
    branches:
      - user/adinath/test
  workflow_dispatch:
  workflow_call:

jobs:
  MetaDataStage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo        
        uses: actions/checkout@v2
      - name: JSON
        shell: pwsh
        run: |
          write-host "welcome"
          $res =  get-content -Path './*.txt'
          write-host $res

  call-workflow-1:
    needs: MetaDataStage
    uses: Adinath-Dukare-382/TestDeleteBranch/.github/workflows/merge.yml@user/adinath/test

  TestNewStage:
    runs-on: label1
    needs: call-workflow-1
    steps:
      - name: check out repo
        uses: actions/checkout@v2
      - name: check new stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Sync
          token: ${{ secrets.GITHUB_TOKEN }}
