name: TestingPath
on:
  push:
    branches:
      - user/adinath/test

jobs:
  MetaDataStage:
    runs-on: label1
    steps:
      - name: Check out repo        
        uses: actions/checkout@v2
      - name: JSON
        shell: pwsh
        run: |
          write-host "welcome"
          $res =  get-content -Path './*.txt'
          write-host $res
