name: TestingPath
on:
  push:
    branches:
      - user/adinath/test

jobs:
  MetaDataStage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo        
        uses: actions/checkout@v2
      - name: JSON
        shell: pwsh
        run: |
          write-host "welcome"
          $res =  get-content -Path './*.txt'
          write-host $res

  TestNewStage:
    runs-on: label1
    needs: MetaDataStage
    steps:
      - name: check out repo
        uses: actions/checkout@v2
      - name: check new stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: sync-branches
          token: ${{ secrets.GITHUB_TOKEN }}
