name: TestingPath
on:
  push:
    branches:
      - user/adinath/test
  workflow_dispatch:

jobs:
  MetaDataStage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo        
        uses: actions/checkout@v2
      - name: JSON
        shell: pwsh
        run: |
          write-host "welcome"
          write-host ${github.workspace}
          write-host ${github.artifactstagingdirectory}
          $res =  get-content -Path './*.txt'
          write-host $res

  call-workflow-1:
    needs: MetaDataStage
    uses: ./.github/workflows/merge.yml
    with:
        input1: "adinath"

  #TestNewStage1:
  #  runs-on: label1
  #  needs: call-workflow-1
  #  steps:
  #    - name: check out repo
  #      uses: actions/checkout@v2
  #    - name: check new stage
  #      uses: ./.github/workflows/merge.yml
  #      with:
  #        #workflow: Sync
  #        token: ${{ secrets.GITHUB_TOKEN }}

  TestNewStage2:
    runs-on: label1
    needs: call-workflow-1
    steps:
      - name: check out repo
        uses: actions/checkout@v2
      - name: check new stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Sync
          token: ${{ secrets.GITHUB_TOKEN }}
